coverage:
  range: 25..75
  round: up
  precision: 0
  status:
    project: off
    patch: off
github_checks: false

flag_management:
  individual_flags:
    - name: smart-tests
      carryforward: true
      carryforward_mode: "labels"
      statuses:
        - type: "project"
        - type: "patch"
        
cli:
  plugins:
    pycoverage:
      report_type: "json"